version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: dockerFile
    environment:
      TZ: Asia/Seoul
    ports:
      - 8000:8000
    volumes:
      - ./src:/usr/app/src
    env_file:
      - ./.docker.env

  database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'lifefoodlog'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: Asia/Seoul
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379
