version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/app/src
      - ./common:/usr/app/common
    env_file:
      - ./env.docker

  database:
    platform: linux/x86_64
    image: mysql:lastest
    environment:
      MYSQL_DATABASE: 'LifeFoodLog'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379
